[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  PRISMA_GENERATE_FORCE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_version = "20"
